version: "2"

linters:
  default: none
  enable:
    - gosec
    - whitespace
    - misspell
    - unconvert
    - unused
    - bodyclose
    - govet
    - staticcheck
  settings:
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Fatalf
    gosec:
      excludes:
        - G401
    gocyclo:
      min-complexity: 10
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2

formatters:
  enable:
    - gofmt
    - goimports
